is_simulation: 0        # Simulation mode
Setting:
  three_stage: 0         # 64QAM mode
  is_simulation: 0        # Simulation mode
  is_keysight: 1          # Keysight mode
  keysight_upsample: 425  # approx any integer
  keysight_upsample_high: 425  # 56GBd mode
  is_tektronic: 0         # Tektronic mode
  is_volterra: 1          # Volterra for kerr effect
  high_rate: 1            # 56GBd mode
  is_QPSK: 0              # For QPSK: 1, 16QAM: 0
  is_RDE: 0               # radius directed Constant modulus algorithm
  two_stage: 1            # First CMA and then RDE
  detail_scan: 1          # Two stage CMA scan only
  is_continue: 1          # denoise of the frequency offset and do Correlation
  is_EB2B: 0              # Activate no dsp processing mode
  downsample_rate: 16   # decision scan point
  first_stage_downsample: 92  # 26GBd mode
  first_stage_downsample_high: 46 # 56GBd mode
  start: 8              # Scan for decision point start
  end: 9              # Scan for decision point tail
  decision_spacing: 1     # Scan for decision point spacing
  longkm: 1               # Activate Chromatic compensation mode
  transport_length: 80    # transmission length
  data_length: 220000      # how much data bits
  record_file: '../Graduate_OB2B_ROP_neg10_400GBD_QAM_op.xlsx' # Record the demodulated result
  cur_dir: '../image_Graduate_OB2B_ROP_neg10_400GBD_QAM_train'    # where to save the demodulated file
  proc_folder: '20211124_400G/80km/highrate/LoP_8_RoP_neg10/'  # which folder save the exp data
  proc_file: 'finisar_56GBd_qam_PN15_600mV.mat' # which exp data file
  Is_pre_volterra: 0 #saving the temp file for volterra tuning
  ctap_far: [13, 15, 5, 7]                       # cma_tap for long transmission
  ctap_B2B: [13, 15, 5, 7] # cma_tap for optical back to back
  volterra_tap: [31, 31, 31]
  volterra_order: 3      # Volterra Filter Order
  cma_batch_size: 150000    # cma batch size for training
  cma_iteration: 20        # cma iteration number
  Nfft: 2048               # chromatic dispersion fft number
  NOverlap: 1024             # chromatic dispersion block overlap
  viterbi_tap: 400           # viterbi tap number
  saving_temp: 0
  viterbi_tap_QPSK: 101    # viterbi tap number for QPSK
  inner_radius: 2.3    #Partition Radius Innter
  outer_radius: 4.0   #Partition Radius Outer


Simulationset:
  symbolpersample: 32
  symbolRate: 120e9       # symbol rate
  is_simulation: 1        # Simulation mode
  is_keysight: 0          # Keysight mode
  keysight_upsample: 425   # approx any integer
  is_tektronic: 0         # Tektronic mode
  is_volterra: 1          # Volterra for kerr effect
  high_rate: 0            # 56GBd mode
  is_QPSK: 0              # For QPSK: 1, 16QAM: 0
  is_RDE: 0               # radius directed Constant modulus algorithm
  two_stage: 1            # First CMA and then RDE
  detail_scan: 1          # Two stage CMA scan only
  is_continue: 1          # denoise of the frequency offset and do Correlation
  is_EB2B: 0              # Activate no dsp processing mode
  downsample_rate: 1     # decision scan point
  first_stage_downsample: 1 # 26GBd mode
  first_stage_downsample_high: 1 # 56GBd mode
  start: 0          # Scan for decision point start
  end: 1             # Scan for decision point tail
  decision_spacing:  1    # Scan for decision point spacing
  longkm:  0              # Activate Chromatic compensation mode
  transport_length: 10     # transmission length
  data_length: 220000      # how much data bits
  record_file: '../simul_16QAM_dualarm_10km_wo_bW_wn_Oband_OSNR36.xlsx' # Record the demodulated result
  cur_dir: '../image_simul_16QAM_dualarm_10km_wo_bW_wn_Oband_OSNR36'    # where to save the demodulated file
  proc_folder: '800GbE_16QAM_dualarm_10km_wo_bW_wn_Oband_OSNR36/'       # which folder save the exp data
  proc_file: 'could_ignore'                                            # which exp data file
  ctap_far: [25, 27, 11, 13]                                           # cma_tap for long transmission
  ctap_B2B: [25, 27, 5, 7]                                        # cma_tap for optical back to back
  volterra_tap: [31, 31, 31]
  volterra_order: 3      # Volterra Filter Order
  cma_batch_size: 150000    # cma batch size for training
  cma_iteration: 20        # cma iteration number
  Nfft: 4096               # chromatic dispersion fft number
  NOverlap: 66             # chromatic dispersion block overlap
  viterbi_tap: 400         # viterbi tap number
  viterbi_tap_QPSK: 101    # viterbi tap number for QPSK
  inner_radius: 2.3    #Partition Radius Innter
  outer_radius: 4.0   #Partition Radius Outer
  keysight_upsample_high: 82  # 56GBd mode
  exp_line: 0
  phase_temp_file_x: 'test_phase_x.txt'
  phase_temp_file_y: 'test_phase_y.txt'
  constellation_tap: 5
  volttera_tap_1: 7
  volttera_tap_2: 21
  volttera_tap_3: 41
  maximum_likelihood_tap: 70
  is_phase_voltera: 1
  is_phase_search: 0
  saving_temp: 0
  temp_file_x: './debug_data/cor_data_x.txt'
  temp_file_y: './debug_data/cor_data_y.txt'
